# Generated by Django 4.1.4 on 2022-12-16 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0004_trackerlog"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TrackerLog",
            new_name="Log",
        ),
    ]
