# Generated by Django 4.1.4 on 2022-12-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0006_alter_log_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
