# Generated by Django 4.1.4 on 2022-12-16 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0007_alter_log_description"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Record",
            new_name="Category",
        ),
    ]
