# Generated by Django 4.1.4 on 2022-12-17 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0008_rename_record_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="log",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="records.category",
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="date",
            field=models.DateField(),
        ),
    ]
