# Generated by Django 4.1.4 on 2022-12-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0009_log_time_alter_log_category_alter_log_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
